"use client";
import { ReactLenis } from "@studio-freight/react-lenis";
import { useEffect } from "react";
import isTouchDevice from "./utils/isTouch";

export default function RootLayout({ children }) {
  useEffect(() => {
    const htmlElement = document.documentElement;

    if (isTouchDevice()) {
      htmlElement.classList.add("touch");
    } else {
      htmlElement.classList.remove("touch");
    }

    const setIsScroll = () => {
      let documentElement = document.documentElement;
      if (window.scrollY > 0) {
        documentElement.classList.add("scroll");
      } else {
        documentElement.classList.remove("scroll");
      }
    };

    const setIsVerticalScroll = () => {
      let documentElement = document.documentElement;
      if (
        window.scrollY > 0 &&
        document.documentElement.classList.contains("touch")
      ) {
        documentElement.classList.add("horizontal-scroll");
      } else if (
        window.scrollY > window.outerWidth &&
        !document.documentElement.classList.contains("touch")
      ) {
        documentElement.classList.add("horizontal-scroll");
      } else {
        documentElement.classList.remove("horizontal-scroll");
      }
      console.log(documentElement.classList);
      console.log("documentElement.classList");
    };

    document.addEventListener("DOMContentLoaded", setIsScroll);
    window.addEventListener("scroll", setIsScroll);
    document.addEventListener("DOMContentLoaded", setIsVerticalScroll);
    window.addEventListener("scroll", setIsVerticalScroll);

    return () => {
      window.removeEventListener("scroll", setIsScroll);
      window.removeEventListener("scroll", setIsVerticalScroll);
    };
  }, []);
  return (
    <html lang="en">
      <head>
        <title>Max Technique</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <ReactLenis
          root
          options={{ lerp: 0.1, duration: 1.5, smoothTouch: true }}
        >
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
